name = "1010163"
main = "workers-site/index.js"
compatibility_date = "2025-07-15"

[site]
bucket = "./public"

[env.production]
name = "my-static-site-prod"

[[migrations]]
tag = "v2"
deleted_classes = ["Globe"]
